
# This workflow is named to uniquely identify it
# within the GitHub Actions UI.

name: Test

# This GitHub Actions workflow is triggered on push
# and pull request events to the "hogwarts" branch.

on:
  push:
    branches: [ hogwarts ]
  pull_request:
    branches: [ hogwarts ]

# GitHub Actions are defined by jobs, which specify
# the tasks to be performed. Every job is executed
# in its own runner environment.

jobs:

  # Define a job named 'run-test'.

  run-test:

    # Define the strategy for running this job, including
    # matrix configurations.

    strategy:

      # 'fail-fast' specifies whether to stop running
      # other matrix jobs if one fails. Setting 'fail-fast'
      # to false means other jobs will continue even if one fails.

      fail-fast: false

      # Matrix configuration allows running this job with different
      # versions of Node.js.

      matrix:

        # Define a matrix with different Node.js versions.

        node-version: [ 22.x ]

    # Name the job with the Node.js version being used in the matrix.

    name: Node v${{ matrix.node-version }}

    # The 'runs-on' parameter designates the virtual machine (VM)
    # type for the job execution. On the other hand, 'ubuntu-latest'
    # indicates that the job will be executed on the most recent
    # version of an Ubuntu VM.

    runs-on: ubuntu-latest

    # 'steps' refer to a series of actions or commands that need to
    # be carried out in this task. Each step has the ability to execute
    # a command, utilize an action, or complete various other tasks.

    steps:

      # Checkout the repository to the GitHub runner to make the code
      # available for the job.

      - uses: actions/checkout@v4

      # Set up the Node.js environment for the job based on the
      # specified version in the matrix.

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Clean installation of dependencies based on the exact
      # versions specified in package-lock.json.

      - name: Clean installation.
        run: npm ci

      # Run tests defined in the 'unit:test' script in package.json.

      - name: Performs unit tests.
        run: npm run unit:test

    # Run tests defined in the 'acceptance:test' script in package.json.

      - name: Performs acceptance tests.
        run: npm run acceptance:test
